# Generated by Django 3.2.1 on 2021-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='reason',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
    ]
