# Generated by Django 3.2.1 on 2021-10-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internal_name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='descripción')),
                ('purchase_available', models.BooleanField(default=True, verbose_name='disponible venta individual')),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internal_name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='descripción')),
                ('purchase_available', models.BooleanField(default=True, verbose_name='disponible venta individual')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('participant_number', models.IntegerField(default=1, verbose_name='numero de participantes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio de venta')),
                ('activities', models.ManyToManyField(to='core.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='descripción')),
                ('color', models.CharField(default='FFFFFF', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='imagen')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.box')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='box',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='categoría'),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='imagen')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reasons',
            field=models.ManyToManyField(blank=True, to='core.Reason', verbose_name='tags'),
        ),
    ]
